-- GENERATED FILE -- do not hand-edit.
-- Produced by work/tools/parse_ability_data.py from
-- references/Pokemon_Colosseum_Abilities_First_251.txt (species mapping)
-- plus hand-authored mechanical metadata for each currently implemented
-- ability. GC6E01 numeric identities for the complete retail 1..77 bank live
-- in `byNumeric` below; source-known but unresolved mechanics stay out of byId.
local AbilityData = {}

AbilityData.bySpecies = {
  [1] = {"OVERGROW"},
  [2] = {"OVERGROW"},
  [3] = {"OVERGROW"},
  [4] = {"BLAZE"},
  [5] = {"BLAZE"},
  [6] = {"BLAZE"},
  [7] = {"TORRENT"},
  [8] = {"TORRENT"},
  [9] = {"TORRENT"},
  [10] = {"SHIELD_DUST"},
  [11] = {"SHED_SKIN"},
  [12] = {"COMPOUNDEYES"},
  [13] = {"SHIELD_DUST"},
  [14] = {"SHED_SKIN"},
  [15] = {"SWARM"},
  [16] = {"KEEN_EYE"},
  [17] = {"KEEN_EYE"},
  [18] = {"KEEN_EYE"},
  [19] = {"GUTS", "RUN_AWAY"},
  [20] = {"GUTS", "RUN_AWAY"},
  [21] = {"KEEN_EYE"},
  [22] = {"KEEN_EYE"},
  [23] = {"INTIMIDATE", "SHED_SKIN"},
  [24] = {"INTIMIDATE", "SHED_SKIN"},
  [25] = {"STATIC"},
  [26] = {"STATIC"},
  [27] = {"SAND_VEIL"},
  [28] = {"SAND_VEIL"},
  [29] = {"POISON_POINT"},
  [30] = {"POISON_POINT"},
  [31] = {"POISON_POINT"},
  [32] = {"POISON_POINT"},
  [33] = {"POISON_POINT"},
  [34] = {"POISON_POINT"},
  [35] = {"CUTE_CHARM"},
  [36] = {"CUTE_CHARM"},
  [37] = {"FLASH_FIRE"},
  [38] = {"FLASH_FIRE"},
  [39] = {"CUTE_CHARM"},
  [40] = {"CUTE_CHARM"},
  [41] = {"INNER_FOCUS"},
  [42] = {"INNER_FOCUS"},
  [43] = {"CHLOROPHYLL"},
  [44] = {"CHLOROPHYLL"},
  [45] = {"CHLOROPHYLL"},
  [46] = {"EFFECT_SPORE"},
  [47] = {"EFFECT_SPORE"},
  [48] = {"COMPOUNDEYES"},
  [49] = {"SHIELD_DUST"},
  [50] = {"ARENA_TRAP", "SAND_VEIL"},
  [51] = {"ARENA_TRAP", "SAND_VEIL"},
  [52] = {"PICKUP"},
  [53] = {"LIMBER"},
  [54] = {"CLOUD_NINE", "DAMP"},
  [55] = {"CLOUD_NINE", "DAMP"},
  [56] = {"VITAL_SPIRIT"},
  [57] = {"VITAL_SPIRIT"},
  [58] = {"FLASH_FIRE", "INTIMIDATE"},
  [59] = {"FLASH_FIRE", "INTIMIDATE"},
  [60] = {"DAMP", "WATER_ABSORB"},
  [61] = {"DAMP", "WATER_ABSORB"},
  [62] = {"DAMP", "WATER_ABSORB"},
  [63] = {"INNER_FOCUS", "SYNCHRONIZE"},
  [64] = {"INNER_FOCUS", "SYNCHRONIZE"},
  [65] = {"INNER_FOCUS", "SYNCHRONIZE"},
  [66] = {"GUTS"},
  [67] = {"GUTS"},
  [68] = {"GUTS"},
  [69] = {"CHLOROPHYLL"},
  [70] = {"CHLOROPHYLL"},
  [71] = {"CHLOROPHYLL"},
  [72] = {"CLEAR_BODY", "LIQUID_OOZE"},
  [73] = {"CLEAR_BODY", "LIQUID_OOZE"},
  [74] = {"ROCK_HEAD", "STURDY"},
  [75] = {"ROCK_HEAD", "STURDY"},
  [76] = {"ROCK_HEAD", "STURDY"},
  [77] = {"FLASH_FIRE", "RUN_AWAY"},
  [78] = {"FLASH_FIRE", "RUN_AWAY"},
  [79] = {"OBLIVIOUS", "OWN_TEMPO"},
  [80] = {"OBLIVIOUS", "OWN_TEMPO"},
  [81] = {"MAGNET_PULL", "STURDY"},
  [82] = {"MAGNET_PULL", "STURDY"},
  [83] = {"INNER_FOCUS", "KEEN_EYE"},
  [84] = {"EARLY_BIRD", "RUN_AWAY"},
  [85] = {"EARLY_BIRD", "RUN_AWAY"},
  [86] = {"THICK_FAT"},
  [87] = {"THICK_FAT"},
  [88] = {"STENCH", "STICKY_HOLD"},
  [89] = {"STENCH", "STICKY_HOLD"},
  [90] = {"SHELL_ARMOR"},
  [91] = {"SHELL_ARMOR"},
  [92] = {"LEVITATE"},
  [93] = {"LEVITATE"},
  [94] = {"LEVITATE"},
  [95] = {"ROCK_HEAD", "STURDY"},
  [96] = {"INSOMNIA"},
  [97] = {"INSOMNIA"},
  [98] = {"HYPER_CUTTER", "SHELL_ARMOR"},
  [99] = {"HYPER_CUTTER", "SHELL_ARMOR"},
  [100] = {"SOUNDPROOF", "STATIC"},
  [101] = {"SOUNDPROOF", "STATIC"},
  [102] = {"CHLOROPHYLL"},
  [103] = {"CHLOROPHYLL"},
  [104] = {"LIGHTNINGROD", "ROCK_HEAD"},
  [105] = {"LIGHTNINGROD", "ROCK_HEAD"},
  [106] = {"LIMBER"},
  [107] = {"KEEN_EYE"},
  [108] = {"OBLIVIOUS", "OWN_TEMPO"},
  [109] = {"LEVITATE"},
  [110] = {"LEVITATE"},
  [111] = {"LIGHTNINGROD", "ROCK_HEAD"},
  [112] = {"LIGHTNINGROD", "ROCK_HEAD"},
  [113] = {"NATURAL_CURE", "SERENE_GRACE"},
  [114] = {"CHLOROPHYLL"},
  [115] = {"EARLY_BIRD"},
  [116] = {"SWIFT_SWIM"},
  [117] = {"POISON_POINT"},
  [118] = {"SWIFT_SWIM", "WATER_VEIL"},
  [119] = {"SWIFT_SWIM", "WATER_VEIL"},
  [120] = {"ILLUMINATE", "NATURAL_CURE"},
  [121] = {"ILLUMINATE", "NATURAL_CURE"},
  [122] = {"SOUNDPROOF"},
  [123] = {"SWARM"},
  [124] = {"OBLIVIOUS"},
  [125] = {"STATIC"},
  [126] = {"FLAME_BODY"},
  [127] = {"HYPER_CUTTER"},
  [128] = {"INTIMIDATE"},
  [129] = {"SWIFT_SWIM"},
  [130] = {"INTIMIDATE"},
  [131] = {"SHELL_ARMOR", "WATER_ABSORB"},
  [132] = {"LIMBER"},
  [133] = {"RUN_AWAY"},
  [134] = {"WATER_ABSORB"},
  [135] = {"VOLT_ABSORB"},
  [136] = {"FLASH_FIRE"},
  [137] = {"TRACE"},
  [138] = {"SHELL_ARMOR", "SWIFT_SWIM"},
  [139] = {"SHELL_ARMOR", "SWIFT_SWIM"},
  [140] = {"BATTLE_ARMOR", "SWIFT_SWIM"},
  [141] = {"BATTLE_ARMOR", "SWIFT_SWIM"},
  [142] = {"PRESSURE", "ROCK_HEAD"},
  [143] = {"IMMUNITY", "THICK_FAT"},
  [144] = {"PRESSURE"},
  [145] = {"PRESSURE"},
  [146] = {"PRESSURE"},
  [147] = {"SHED_SKIN"},
  [148] = {"SHED_SKIN"},
  [149] = {"INNER_FOCUS"},
  [150] = {"PRESSURE"},
  [151] = {"SYNCHRONIZE"},
  [152] = {"OVERGROW"},
  [153] = {"OVERGROW"},
  [154] = {"OVERGROW"},
  [155] = {"BLAZE"},
  [156] = {"BLAZE"},
  [157] = {"BLAZE"},
  [158] = {"TORRENT"},
  [159] = {"TORRENT"},
  [160] = {"TORRENT"},
  [161] = {"KEEN_EYE", "RUN_AWAY"},
  [162] = {"KEEN_EYE", "RUN_AWAY"},
  [163] = {"INSOMNIA", "KEEN_EYE"},
  [164] = {"INSOMNIA", "KEEN_EYE"},
  [165] = {"EARLY_BIRD", "SWARM"},
  [166] = {"EARLY_BIRD", "SWARM"},
  [167] = {"INSOMNIA", "SWARM"},
  [168] = {"INSOMNIA", "SWARM"},
  [169] = {"INNER_FOCUS"},
  [170] = {"ILLUMINATE", "VOLT_ABSORB"},
  [171] = {"ILLUMINATE", "VOLT_ABSORB"},
  [172] = {"STATIC"},
  [173] = {"CUTE_CHARM"},
  [174] = {"CUTE_CHARM"},
  [175] = {"HUSTLE", "SERENE_GRACE"},
  [176] = {"HUSTLE", "SERENE_GRACE"},
  [177] = {"EARLY_BIRD", "SYNCHRONIZE"},
  [178] = {"EARLY_BIRD", "SYNCHRONIZE"},
  [179] = {"STATIC"},
  [180] = {"STATIC"},
  [181] = {"STATIC"},
  [182] = {"CHLOROPHYLL"},
  [183] = {"HUGE_POWER", "THICK_FAT"},
  [184] = {"HUGE_POWER", "THICK_FAT"},
  [185] = {"ROCK_HEAD", "STURDY"},
  [186] = {"DAMP", "WATER_ABSORB"},
  [187] = {"CHLOROPHYLL"},
  [188] = {"CHLOROPHYLL"},
  [189] = {"CHLOROPHYLL"},
  [190] = {"PICKUP", "RUN_AWAY"},
  [191] = {"CHLOROPHYLL"},
  [192] = {"CHLOROPHYLL"},
  [193] = {"COMPOUNDEYES", "SPEED_BOOST"},
  [194] = {"DAMP", "WATER_ABSORB"},
  [195] = {"DAMP", "WATER_ABSORB"},
  [196] = {"SYNCHRONIZE"},
  [197] = {"SYNCHRONIZE"},
  [198] = {"INSOMNIA"},
  [199] = {"OBLIVIOUS", "OWN_TEMPO"},
  [200] = {"LEVITATE"},
  [201] = {"LEVITATE"},
  [202] = {"SHADOW_TAG"},
  [203] = {"EARLY_BIRD", "INNER_FOCUS"},
  [204] = {"STURDY"},
  [205] = {"STURDY"},
  [206] = {"RUN_AWAY", "SERENE_GRACE"},
  [207] = {"HYPER_CUTTER", "SAND_VEIL"},
  [208] = {"ROCK_HEAD", "STURDY"},
  [209] = {"INTIMIDATE", "RUN_AWAY"},
  [210] = {"INTIMIDATE"},
  [211] = {"POISON_POINT", "SWIFT_SWIM"},
  [212] = {"SWARM"},
  [213] = {"STURDY"},
  [214] = {"GUTS", "SWARM"},
  [215] = {"INNER_FOCUS", "KEEN_EYE"},
  [216] = {"PICKUP"},
  [217] = {"GUTS"},
  [218] = {"FLAME_BODY", "MAGMA_ARMOR"},
  [219] = {"FLAME_BODY", "MAGMA_ARMOR"},
  [220] = {"OBLIVIOUS"},
  [221] = {"OBLIVIOUS"},
  [222] = {"HUSTLE", "NATURAL_CURE"},
  [223] = {"HUSTLE"},
  [224] = {"SUCTION_CUPS"},
  [225] = {"HUSTLE", "VITAL_SPIRIT"},
  [226] = {"SWIFT_SWIM", "WATER_ABSORB"},
  [227] = {"KEEN_EYE", "STURDY"},
  [228] = {"EARLY_BIRD", "FLASH_FIRE"},
  [229] = {"EARLY_BIRD", "FLASH_FIRE"},
  [230] = {"SWIFT_SWIM"},
  [231] = {"PICKUP"},
  [232] = {"STURDY"},
  [233] = {"TRACE"},
  [234] = {"INTIMIDATE"},
  [235] = {"OWN_TEMPO"},
  [236] = {"GUTS"},
  [237] = {"INTIMIDATE"},
  [238] = {"OBLIVIOUS"},
  [239] = {"STATIC"},
  [240] = {"FLAME_BODY"},
  [241] = {"THICK_FAT"},
  [242] = {"NATURAL_CURE", "SERENE_GRACE"},
  [243] = {"PRESSURE"},
  [244] = {"PRESSURE"},
  [245] = {"PRESSURE"},
  [246] = {"GUTS"},
  [247] = {"SHED_SKIN"},
  [248] = {"SAND_STREAM"},
  [249] = {"PRESSURE"},
  [250] = {"PRESSURE"},
  [251] = {"NATURAL_CURE"},
}

AbilityData.byId = {
  ARENA_TRAP = {display="Arena Trap", category="trap_block"},
  BATTLE_ARMOR = {display="Battle Armor", category="crit_immune"},
  BLAZE = {display="Blaze", category="low_hp_power", moveType="FIRE", multiplier=1.5, threshold=0.3333333333333333},
  CHLOROPHYLL = {display="Chlorophyll", category="weather_speed", weather="sun", multiplier=2},
  CLEAR_BODY = {display="Clear Body", category="stat_veto", stat="ALL"},
  CLOUD_NINE = {display="Cloud Nine", category="weather_suppress"},
  COMPOUNDEYES = {display="Compound Eyes", category="accuracy_mult_self", multiplier=1.3},
  CUTE_CHARM = {display="Cute Charm", category="contact_reactive", effect="ATTRACT", chance=0.3333333333333333},
  DAMP = {display="Damp", category="field_move_veto", moves={"SELFDESTRUCT", "EXPLOSION"}},
  EARLY_BIRD = {display="Early Bird", category="sleep_duration", multiplier=0.5},
  EFFECT_SPORE = {display="Effect Spore", category="contact_reactive", effect="RANDOM_MINOR", chance=0.1, options={"PSN", "PAR", "SLP"}},
  FLAME_BODY = {display="Flame Body", category="contact_reactive", effect="BRN", chance=0.3333333333333333},
  FLASH_FIRE = {display="Flash Fire", category="type_immune_boost", moveType="FIRE", multiplier=1.5},
  GUTS = {display="Guts", category="status_attack_boost", multiplier=1.5},
  HUGE_POWER = {display="Huge Power", category="flat_stat_double", stat="attack"},
  HUSTLE = {display="Hustle", category="attack_boost_accuracy_penalty", attackMultiplier=1.5, accuracyMultiplier=0.8},
  HYPER_CUTTER = {display="Hyper Cutter", category="stat_veto", stat="attack"},
  ILLUMINATE = {display="Illuminate", category="no_battle_effect"},
  IMMUNITY = {display="Immunity", category="status_veto", status="PSN"},
  INNER_FOCUS = {display="Inner Focus", category="flinch_veto"},
  INSOMNIA = {display="Insomnia", category="status_veto", status="SLP"},
  INTIMIDATE = {display="Intimidate", category="switch_in_stat", stat="attack", stages=-1, target="opponents"},
  KEEN_EYE = {display="Keen Eye", category="stat_veto", stat="accuracy"},
  LEVITATE = {display="Levitate", category="type_immune", moveType="GROUND", alsoImmune={"SPIKES", "ARENA_TRAP"}},
  LIGHTNINGROD = {display="Lightning Rod", category="redirect", moveType="ELECTRIC"},
  LIMBER = {display="Limber", category="status_veto", status="PAR"},
  LIQUID_OOZE = {display="Liquid Ooze", category="drain_punish", excludeEffect="DREAM_EATER_EFFECT"},
  MAGMA_ARMOR = {display="Magma Armor", category="status_veto", status="FRZ"},
  MAGNET_PULL = {display="Magnet Pull", category="trap_block", trapType="STEEL"},
  MARVEL_SCALE = {display="Marvel Scale", category="status_defense_boost", multiplier=1.5},
  NATURAL_CURE = {display="Natural Cure", category="switch_out_cure"},
  OBLIVIOUS = {display="Oblivious", category="infatuation_veto"},
  OVERGROW = {display="Overgrow", category="low_hp_power", moveType="GRASS", multiplier=1.5, threshold=0.3333333333333333},
  OWN_TEMPO = {display="Own Tempo", category="confusion_veto"},
  PICKUP = {display="Pickup", category="no_battle_effect"},
  PLUS = {display="Plus", category="field_partner_special_boost", partnerAbility="MINUS", multiplier=1.5},
  POISON_POINT = {display="Poison Point", category="contact_reactive", effect="PSN", chance=0.3333333333333333},
  PRESSURE = {display="Pressure", category="pp_cost", extra=1},
  -- GC6E01 damage setup treats ability 0x4A (Pure Power) in the exact same
  -- pre-formula Attack-double branch as 0x25 (Huge Power).
  PURE_POWER = {display="Pure Power", category="flat_stat_double", stat="attack"},
  MINUS = {display="Minus", category="field_partner_special_boost", partnerAbility="PLUS", multiplier=1.5},
  ROUGH_SKIN = {display="Rough Skin", category="contact_damage", fraction=0.0625},
  ROCK_HEAD = {display="Rock Head", category="recoil_veto", excludeEffects={"SHADOW_RUSH", "STRUGGLE"}},
  RUN_AWAY = {display="Run Away", category="wild_escape"},
  SAND_STREAM = {display="Sand Stream", category="switch_in_weather", weather="sandstorm", turns="infinite"},
  SAND_VEIL = {display="Sand Veil", category="weather_accuracy_defense", weather="sandstorm", multiplier=0.8, chipImmune=true},
  SERENE_GRACE = {display="Serene Grace", category="secondary_chance_double"},
  SHADOW_TAG = {display="Shadow Tag", category="trap_block", trapType="ALL"},
  SHED_SKIN = {display="Shed Skin", category="end_of_turn_cure", chance=0.3333333333333333},
  SHELL_ARMOR = {display="Shell Armor", category="crit_immune"},
  SHIELD_DUST = {display="Shield Dust", category="secondary_effect_veto_self"},
  SOUNDPROOF = {display="Soundproof", category="sound_move_immune"},
  SPEED_BOOST = {display="Speed Boost", category="end_of_turn_stat", stat="speed", stages=1},
  STATIC = {display="Static", category="contact_reactive", effect="PAR", chance=0.3333333333333333},
  STENCH = {display="Stench", category="no_battle_effect"},
  STICKY_HOLD = {display="Sticky Hold", category="item_protect"},
  STURDY = {display="Sturdy", category="ohko_block"},
  SUCTION_CUPS = {display="Suction Cups", category="forced_switch_veto"},
  SWARM = {display="Swarm", category="low_hp_power", moveType="BUG", multiplier=1.5, threshold=0.3333333333333333},
  SWIFT_SWIM = {display="Swift Swim", category="weather_speed", weather="rain", multiplier=2},
  SYNCHRONIZE = {display="Synchronize", category="status_reflect", statuses={"BRN", "PSN", "PAR"}},
  THICK_FAT = {display="Thick Fat", category="type_damage_half", moveTypes={"FIRE", "ICE"}},
  TORRENT = {display="Torrent", category="low_hp_power", moveType="WATER", multiplier=1.5, threshold=0.3333333333333333},
  TRACE = {display="Trace", category="switch_in_copy_ability"},
  VITAL_SPIRIT = {display="Vital Spirit", category="status_veto", status="SLP"},
  VOLT_ABSORB = {display="Volt Absorb", category="type_absorb_heal", moveType="ELECTRIC", healFraction=0.25},
  WATER_ABSORB = {display="Water Absorb", category="type_absorb_heal", moveType="WATER", healFraction=0.25},
  WATER_VEIL = {display="Water Veil", category="status_veto", status="BRN"},
  WHITE_SMOKE = {display="White Smoke", category="stat_veto", stat="ALL"},
  -- GC6E01 ability 0x19: ordinary damaging hits pass only when their final
  -- type multiplier is super-effective (>10 on both supported host kernels).
  -- Status moves are not vetoed. Move/effect-specific retail exceptions remain
  -- isolated at their own source-backed handlers rather than guessed here.
  WONDER_GUARD = {display="Wonder Guard", category="wonder_guard"},
}

-- Retail GC6E01 PokemonStats stores numeric Gen-III ability ids for all 386
-- species. Keep this canonical id map separate from `byId`: an id can be
-- source-known while its runtime mechanic is still deliberately unsupported.
-- Abilities.resolve uses the numeric map to select the retail slot first, then
-- returns it only when `byId[name]` has an implemented mechanic/declared effect.
AbilityData.byNumeric = {
  [1]="STENCH",[2]="DRIZZLE",[3]="SPEED_BOOST",[4]="BATTLE_ARMOR",
  [5]="STURDY",[6]="DAMP",[7]="LIMBER",[8]="SAND_VEIL",[9]="STATIC",
  [10]="VOLT_ABSORB",[11]="WATER_ABSORB",[12]="OBLIVIOUS",[13]="CLOUD_NINE",
  [14]="COMPOUNDEYES",[15]="INSOMNIA",[16]="COLOR_CHANGE",[17]="IMMUNITY",
  [18]="FLASH_FIRE",[19]="SHIELD_DUST",[20]="OWN_TEMPO",[21]="SUCTION_CUPS",
  [22]="INTIMIDATE",[23]="SHADOW_TAG",[24]="ROUGH_SKIN",[25]="WONDER_GUARD",
  [26]="LEVITATE",[27]="EFFECT_SPORE",[28]="SYNCHRONIZE",[29]="CLEAR_BODY",
  [30]="NATURAL_CURE",[31]="LIGHTNINGROD",[32]="SERENE_GRACE",[33]="SWIFT_SWIM",
  [34]="CHLOROPHYLL",[35]="ILLUMINATE",[36]="TRACE",[37]="HUGE_POWER",
  [38]="POISON_POINT",[39]="INNER_FOCUS",[40]="MAGMA_ARMOR",[41]="WATER_VEIL",
  [42]="MAGNET_PULL",[43]="SOUNDPROOF",[44]="RAIN_DISH",[45]="SAND_STREAM",
  [46]="PRESSURE",[47]="THICK_FAT",[48]="EARLY_BIRD",[49]="FLAME_BODY",
  [50]="RUN_AWAY",[51]="KEEN_EYE",[52]="HYPER_CUTTER",[53]="PICKUP",
  [54]="TRUANT",[55]="HUSTLE",[56]="CUTE_CHARM",[57]="PLUS",[58]="MINUS",
  [59]="FORECAST",[60]="STICKY_HOLD",[61]="SHED_SKIN",[62]="GUTS",
  [63]="MARVEL_SCALE",[64]="LIQUID_OOZE",[65]="OVERGROW",[66]="BLAZE",
  [67]="TORRENT",[68]="SWARM",[69]="ROCK_HEAD",[70]="DROUGHT",
  [71]="ARENA_TRAP",[72]="VITAL_SPIRIT",[73]="WHITE_SMOKE",[74]="PURE_POWER",
  [75]="SHELL_ARMOR",[76]="CACOPHONY",[77]="AIR_LOCK",
}

AbilityData.contactMoves = {
  BIND = true,
  BITE = true,
  BODY_SLAM = true,
  BONEMERANG = true,
  COMET_PUNCH = true,
  CONSTRICT = true,
  COUNTER = true,
  CROSS_CHOP = true,
  CRUNCH = true,
  CUT = true,
  DIG = true,
  DOUBLESLAP = true,
  DOUBLE_EDGE = true,
  DOUBLE_KICK = true,
  DRILL_PECK = true,
  DYNAMICPUNCH = true,
  EGG_BOMB = true,
  EXPLOSION = true,
  EXTREMESPEED = true,
  FAKE_OUT = true,
  FIRE_PUNCH = true,
  FLAIL = true,
  FLY = true,
  FRUSTRATION = true,
  FURY_ATTACK = true,
  FURY_CUTTER = true,
  GUILLOTINE = true,
  HEADBUTT = true,
  HI_JUMP_KICK = true,
  HORN_ATTACK = true,
  HORN_DRILL = true,
  ICE_PUNCH = true,
  JUMP_KICK = true,
  KARATE_CHOP = true,
  LEECH_LIFE = true,
  LICK = true,
  LOW_KICK = true,
  MACH_PUNCH = true,
  MEGAHORN = true,
  MEGA_KICK = true,
  MEGA_PUNCH = true,
  OUTRAGE = true,
  PAY_DAY = true,
  PECK = true,
  POUND = true,
  PRESENT = true,
  PURSUIT = true,
  RETURN = true,
  REVERSAL = true,
  ROCK_SLIDE = true,
  ROLLING_KICK = true,
  ROLLOUT = true,
  SCRATCH = true,
  SEISMIC_TOSS = true,
  SELFDESTRUCT = true,
  SHADOW_RUSH = true,
  SKULL_BASH = true,
  SLAM = true,
  SLASH = true,
  SMOG = true,
  SNORE = true,
  SPARK = true,
  SPIKE_CANNON = true,
  STOMP = true,
  STRENGTH = true,
  STRUGGLE = true,
  SUBMISSION = true,
  TACKLE = true,
  TAKE_DOWN = true,
  THRASH = true,
  THUNDERPUNCH = true,
  TRIPLE_KICK = true,
  TRI_ATTACK = true,
  VICEGRIP = true,
  VINE_WHIP = true,
  WHIRLWIND = true,
  WING_ATTACK = true,
  WRAP = true,
  ZAP_CANNON = true,
}

return AbilityData
